{
 "title": "LOTUS farcaster",
 "description": "A Filecoin lotus dashboard for miners",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job:",
    "query": {
     "query": "label_values(lotus_miner_info,job)"
    }
   },
   {
    "name": "miner_id",
    "label": "Miner ID",
    "query": {
     "query": "label_values(lotus_miner_info{job=\"$job\"},miner_id)"
    }
   },
   {
    "name": "worker_addr",
    "label": "Worker Address",
    "query": {
     "query": "label_values(lotus_miner_info{job=\"$job\",miner_id=\"$miner_id\"},worker_addr)"
    }
   },
   {
    "name": "owner_addr",
    "label": "Owner Address",
    "query": {
     "query": "label_values(lotus_miner_info{job=\"$job\",miner_id=\"$miner_id\"},owner_addr)"
    }
   },
   {
    "name": "control0_addr",
    "label": "Control Address 0",
    "query": {
     "query": "label_values(lotus_miner_info{job=\"$job\",miner_id=\"$miner_id\"},control0_addr)"
    }
   },
   {
    "name": "worker_host",
    "label": "Worker",
    "query": {
     "query": "query_result(sort(lotus_miner_worker_cpu{job=\"$job\",miner_id=\"$miner_id\"}))"
    }
   },
   {
    "name": "storage_id",
    "label": "Storage",
    "query": {
     "query": "label_values(lotus_miner_storage_info{job=\"$job\",miner_id=\"$miner_id\"},storage_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Retrieval Deals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "On-going Retrieval Data Transfers",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "lotus_miner_data_transfers{job=\"$job\",miner_id=\"$miner_id\", status=\"Ongoing\", is_sender=\"True\"}"
    },
    {
     "expr": "rate(lotus_miner_data_transfers{job=\"$job\",miner_id=\"$miner_id\", status=\"Ongoing\", is_sender=\"True\"}[5m])"
    }
   ]
  },
  {
   "title": "PeerID Throughput",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (other_peer)(rate(lotus_miner_data_transfers{job=\"$job\",miner_id=\"$miner_id\", status=\"Ongoing\", is_sender=\"True\"}[5m]))",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "PeerID concurrent transfers",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (other_peer)(lotus_miner_data_transfers{job=\"$job\",miner_id=\"$miner_id\", status=\"Ongoing\", is_sender=\"`True\"})",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "PeerID Throughput",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (other_peer)(rate(lotus_miner_data_transfers{job=\"$job\",miner_id=\"$miner_id\", status=\"Ongoing\", is_sender=\"True\"}[5m]))",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Storage Deals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "On-going Storage Data Transfers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "lotus_miner_data_transfers{job=\"$job\",miner_id=\"$miner_id\", status=\"Ongoing\", is_sender=\"False\"}"
    },
    {
     "expr": "rate(lotus_miner_data_transfers{job=\"$job\",miner_id=\"$miner_id\", status=\"Ongoing\", is_sender=\"False\"}[5m])"
    }
   ]
  },
  {
   "title": "PeerID Throughput",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (other_peer)(rate(lotus_miner_data_transfers{job=\"$job\",miner_id=\"$miner_id\", status=\"Ongoing\", is_sender=\"False\"}[5m]))",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "PeerID concurrent transfers",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (other_peer)(lotus_miner_data_transfers{job=\"$job\",miner_id=\"$miner_id\", status=\"Ongoing\", is_sender=\"False\"})",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "PeerID Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (other_peer)(rate(lotus_miner_data_transfers{job=\"$job\",miner_id=\"$miner_id\", status=\"Ongoing\", is_sender=\"False\"}[5m]))",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Farcaster Status",
   "type": "table",
   "description": "Status if error it means the last update was in error\nLast update is the last time that lotus-farcaster has been executed on the miner",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "lotus_local_time{job=\"$job\"}",
     "legendFormat": "Last update"
    },
    {
     "expr": "lotus_scrape_execution_succeed{job=\"$job\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_chain_height{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Chain Head"
    }
   ]
  },
  {
   "title": "Is onSync",
   "type": "table",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_chain_sync_status{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Worker {{ worker_id }}"
    }
   ]
  },
  {
   "title": "Quality Adjusted Power",
   "type": "gauge",
   "description": "Quality Adjust Power : Power adjusted with deals / verified deals (x10)\nMAX Quality Adjusted Power : Maximum Quality adjusted power you can expect from the miner after the next deadline ",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"miner\",power_type=\"QualityAdjPower\"}",
     "legendFormat": "QA Power"
    },
    {
     "expr": "sum(lotus_miner_sector_qa_power{job=\"$job\",miner_id=\"$miner_id\"} * on(sector_id) group_left () lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"})",
     "legendFormat": "Max QA Power"
    }
   ]
  },
  {
   "title": "Raw Power",
   "type": "gauge",
   "description": "Quality Adjust Power :  Proving ACTIVE sectors on chain + x10 for verified <= Used for Winning PoST\nRaw Byte Power : Proving ACTIVE sectors on chain\nCommitted Power : Raw power increase for the next deadlines",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"miner\", power_type=\"RawBytePower\"}",
     "legendFormat": "{{power_type}}"
    },
    {
     "expr": "sum( lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\", is_live=\"True\"} * on(miner_id) group_left () lotus_miner_info_sector_size{job=\"$job\",miner_id=\"$miner_id\"})",
     "legendFormat": "Committed Power"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "lotus_power_mining_eligibility{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Mining"
    }
   ]
  },
  {
   "title": "Local Mpool Pending messages",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "lotus_mpool_local_message{job=\"$job\",miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Available Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_wallet_balance{job=\"$job\",miner_id=\"$miner_id\", address=\"$miner_id\"}",
     "legendFormat": "Miner"
    },
    {
     "expr": "lotus_wallet_balance{job=\"$job\",miner_id=\"$miner_id\", address=\"$owner_addr\"}",
     "legendFormat": "Owner"
    },
    {
     "expr": "lotus_wallet_balance{job=\"$job\",miner_id=\"$miner_id\", address=\"$worker_addr\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "lotus_wallet_balance{job=\"$job\",miner_id=\"$miner_id\", address=\"$control0_addr\"}",
     "legendFormat": "Control0"
    }
   ]
  },
  {
   "title": "Netpeers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "lotus_netpeers_total{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "lotus_miner_netpeers_total{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Miner"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_mpool_local_total{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Local mpool pending"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_mpool_total{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": " Mpool pending"
    }
   ]
  },
  {
   "title": "Locked Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_wallet_locked_balance{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "{{locked_type}}"
    }
   ]
  },
  {
   "title": "Sectors with deals",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lotus_miner_sector_weight{job=\"$job\",miner_id=\"$miner_id\", weight_type=\"verified\"} * on(sector_id) group_left () lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"}) - count(lotus_miner_sector_weight{job=\"$job\",miner_id=\"$miner_id\", weight_type=\"verified\"} * on(sector_id) group_left () lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"} > 0) - count(lotus_miner_sector_weight{job=\"$job\",miner_id=\"$miner_id\", weight_type=\"non_verified\"} * on(sector_id) group_left () lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"} > 0)",
     "legendFormat": "CC"
    },
    {
     "expr": "count(lotus_miner_sector_weight{job=\"$job\",miner_id=\"$miner_id\", weight_type=\"verified\"} * on(sector_id) group_left () lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"} > 0)",
     "legendFormat": "Verified"
    },
    {
     "expr": "count(lotus_miner_sector_weight{job=\"$job\",miner_id=\"$miner_id\", weight_type=\"non_verified\"} * on(sector_id) group_left () lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"} > 0)",
     "legendFormat": "Non Verified"
    }
   ]
  },
  {
   "title": "Power estimation",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "1/(sum(lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"miner\", power_type=\"QualityAdjPower\"})/sum(lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"network\",power_type=\"QualityAdjPower\"})*2*5/60)"
    },
    {
     "expr": "sum(lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"miner\", power_type=\"QualityAdjPower\"})/sum(lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"network\",power_type=\"QualityAdjPower\"})*5*60*2*24"
    },
    {
     "expr": "sum(lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"miner\", power_type=\"QualityAdjPower\"})/sum(lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"network\",power_type=\"QualityAdjPower\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "nfarad" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_chain_basefee{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Basefee"
    }
   ]
  },
  {
   "title": "Deadlines",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_miner_deadline_active_start{job=\"$job\",miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_active_sectors_all{job=\"$job\",miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_active_sectors_recovering{job=\"$job\",miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_active_sectors_faulty{job=\"$job\",miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_active_partitions{job=\"$job\",miner_id=\"$miner_id\"}-lotus_miner_deadline_active_partitions_proven{job=\"$job\",miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lotus_wallet_balance {job=\"$job\",miner_id=\"$miner_id\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(lotus_wallet_locked_balance{job=\"$job\",miner_id=\"$miner_id\"})",
     "legendFormat": "Locked"
    }
   ]
  },
  {
   "title": "Other Wallet Balances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_wallet_balance {job=\"$job\",miner_id=\"$miner_id\",address!~\"$worker_addr|$owner_addr|$control0_addr|$miner_id\", name!~\"\"} > 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Verified datacap available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_wallet_verified_datacap{job=\"$job\",miner_id=\"$miner_id\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Sealing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Sealing jobs All (Running VS Idle)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "# REtourne le nombre de JOB dans l'etat running\ncount by (task) (lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\",run_wait=\"0\"})",
     "legendFormat": "{{ task }}"
    },
    {
     "expr": "count by (state) (lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", state!~\"(Proving|Removed)\"} unless on (sector_id) lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\",run_wait=\"0\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(lotus_miner_pending_publish_deal{job=\"$job\",miner_id=\"$miner_id\"})",
     "legendFormat": "Pending Publish"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (state) (lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "count(lotus_miner_sector_state{state=\"Proving\", job=\"$job\",miner_id=\"$miner_id\"} unless on (sector_id) lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"})",
     "legendFormat": "Expired"
    },
    {
     "expr": "count(lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", to_upgrade=\"True\" })",
     "legendFormat": "To Upgrade"
    }
   ]
  },
  {
   "title": "IDLE Sealing Sectors",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "# Retourne tout les secteurs qui sont sur les workers mais dans un statut different de Running. On les enrichis avec les infos des workers (Assigned par exemple)\n(lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", state!~\"(Proving|Removed)\"} * on (sector_id) group_left(job_id,run_wait,job_start_time,task,worker) lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\", run_wait!=\"0\"})*1"
    },
    {
     "expr": "# Retourne les jobs qui sont sur les worker dans un etat different de Running et qui seraient absent de la liste des secteurs (pas sur que ca existe)\n(lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\", run_wait!=\"0\"} unless on (sector_id) (lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", state!~\"(Proving|Removed)\"}))*1"
    },
    {
     "expr": "# Retourne la liste des secteurs qui ne sont pas dans la liste des Jobs (Comme le WAitSeed, WaitCommit, mais aussi d'autres qui traine)\n# Les label_replace servent a creer des colonnes à 0 au cas ou la premiere requete ne retourne rien\n(label_replace(label_replace(label_replace(label_replace(label_replace(lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", state!~\"(Proving|Removed)\"},\"job_id\",\"0\",\"\",\"\"),\"run_wait\",\"98\",\"\",\"\"),\"job_start_time\",\"0\",\"\",\"\"),\"task\",\"0\",\"\",\"\"),\"worker\",\"0\",\"\",\"\") unless on (sector_id) lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\"})*1"
    },
    {
     "expr": "# Retourne la date de creation pour les secteurs. Ici on filtre sur les 2 requetes principales precendente and AND et on les unis avec OR. Les requetes precendetes se terminent par *1 pour perdre le nom de la metrics et s'assurer que la transformation Merge fonctionne.\n((lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"creation\"})  and  on (sector_id) lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\", run_wait!=\"0\"}) or ((lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"creation\"})  and  on (sector_id) (lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", state!~\"(Proving|Removed)\"} unless on (sector_id) lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\"}))"
    }
   ]
  },
  {
   "title": "Pending publish deals",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "lotus_miner_pending_publish_deal{job=\"$job\",miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Average Sealing Duration (From Packed to Finalized)",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "quantile(0.5, (topk(10,lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"finalized\"}) - on (sector_id) lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"packed\"}) and on(sector_id) lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", state=\"Proving\"})",
     "legendFormat": "Last 10 Sectors"
    },
    {
     "expr": "quantile(0.5, (topk(100,lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"finalized\"}) - on (sector_id) lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"packed\"}) and on(sector_id) lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", state=\"Proving\"})",
     "legendFormat": "Last 100 Sectors"
    },
    {
     "expr": "quantile(0.5, (lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"finalized\"} - on (sector_id) lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"packed\"}) and on(sector_id) lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", state=\"Proving\"})",
     "legendFormat": "All times"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count (lotus_miner_worker_cpu{job=\"$job\",miner_id=\"$miner_id\"})",
     "legendFormat": "Number of Workers"
    }
   ]
  },
  {
   "title": "RUNNING Sealing Sectors",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "# Retourne la liste de tout les jobs \"Running\" enrichi aves les informations deals and creation date recuperer depuis la liste des sectors\nlotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\",run_wait=\"0\"} * on (sector_id) group_left(deals,creation_date) (lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\",state!~\"(Proving|Removed)\"})*1"
    },
    {
     "expr": "# Retourne la liste des jobs en cours \"Running\" pour lesquels il n'a a pas encore des secteurs (Les premiers AP par exemple) \nlotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\",run_wait=\"0\"} unless on (sector_id) (lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\",state!~\"(Proving|Removed)\"})*1"
    },
    {
     "expr": "# Calcul do 95 centile sur 30 jours des jobs par Worker et Par task et calcul le temps restant pour chacun des jobs\nlotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\",run_wait=\"0\"} - on(worker_host,task) group_left()(quantile(0.95,(max_over_time(lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\",worker_host!=\"\", run_wait=\"0\"}[30d]) > 1)) by (worker_host,task))"
    },
    {
     "expr": "# Retourne la date de creation du secteur\nlotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\",event_type=\"creation\"} and on(sector_id) lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\",run_wait=\"0\"} "
    }
   ]
  },
  {
   "title": "Sealing Deals",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_miner_sector_sealing_deals_info{job=\"$job\",miner_id=\"$miner_id\"}  * on (sector_id) group_left(state) (lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\"})\n"
    }
   ]
  },
  {
   "title": "Average Job time",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "# Calcul do 95 centile sur 30 jours\nquantile(0.95,(max_over_time(lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\", worker_host!=\"\", run_wait=\"0\"}[30d]) > 1)) by (worker_host,task)",
     "legendFormat": "{{ legend }} - {{ worker_host }}"
    },
    {
     "expr": "# Calcul do 95 centile sur 2 jours\nquantile(0.95,(max_over_time(lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\", worker_host!=\"\", run_wait=\"0\"}[2d]) > 1)) by (worker_host,task)",
     "legendFormat": "{{ legend }} - {{ worker_host }}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_miner_storage_info{job=\"$job\",miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_storage_available{job=\"$job\",miner_id=\"$miner_id\"} "
    },
    {
     "expr": "lotus_miner_storage_available{job=\"$job\",miner_id=\"$miner_id\"} /lotus_miner_storage_capacity{job=\"$job\",miner_id=\"$miner_id\"} "
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Resources - $worker_host",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 59 },
   "repeat": "worker_host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg((lotus_miner_worker_cpu_used{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"})/(lotus_miner_worker_cpu{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}) >= 0)",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg((lotus_miner_worker_gpu_used{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"})/(lotus_miner_worker_gpu{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}) >= 0)",
     "legendFormat": "GPU"
    },
    {
     "expr": "avg((lotus_miner_worker_ram_tasks{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_ram_reserved{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"})/(lotus_miner_worker_ram_total{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}) >= 0)",
     "legendFormat": "RAM"
    },
    {
     "expr": "avg((lotus_miner_worker_vmem_tasks{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_vmem_reserved{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"})/(lotus_miner_worker_vmem_total{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}) >= 0)",
     "legendFormat": "VMEM"
    }
   ]
  },
  { "title": "Config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_info{job=\"$job\",miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Daemon Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_info{job=\"$job\",miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Miner Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_miner_info{job=\"$job\",miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Storage Market Config",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 6, "y": 64 },
   "targets": [
    {
     "expr": "lotus_miner_market_info{job=\"$job\",miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Retrieval Market Config",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "targets": [
    {
     "expr": "lotus_miner_market_info{job=\"$job\",miner_id=\"$miner_id\"}"
    }
   ]
  },
  { "title": "Sealing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Sealing jobs - RUNNING",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "# REtourne le nombre de JOB dans l'etat running\ncount by (task) (lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\",run_wait=\"0\"})",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Sealing jobs - IDLE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "count by (state) ((lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", state!~\"(Proving|Removed)\"}) unless on (sector_id) lotus_miner_worker_job{job=\"$job\",miner_id=\"$miner_id\",run_wait=\"0\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Sealing ERRORS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "count by (state) (lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\" })",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Deals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sectors with deals",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "none", "label": "Sectors" }
     ],
     "targets": [
      {
       "expr": "count(lotus_miner_sector_weight{job=\"$job\",miner_id=\"$miner_id\", weight_type=\"verified\"} * on(sector_id) group_left () lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"} > 0)",
       "legendFormat": "Verified"
      },
      {
       "expr": "count(lotus_miner_sector_weight{job=\"$job\",miner_id=\"$miner_id\", weight_type=\"non_verified\"} * on(sector_id) group_left () lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"} > 0)",
       "legendFormat": "Non Verified"
      },
      {
       "expr": "count(lotus_miner_sector_weight{job=\"$job\",miner_id=\"$miner_id\", weight_type=\"verified\"} * on(sector_id) group_left () lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"}) - count(lotus_miner_sector_weight{job=\"$job\",miner_id=\"$miner_id\", weight_type=\"verified\"} * on(sector_id) group_left () lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"} > 0) - count(lotus_miner_sector_weight{job=\"$job\",miner_id=\"$miner_id\", weight_type=\"non_verified\"} * on(sector_id) group_left () lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"} > 0)",
       "legendFormat": "CC"
      }
     ]
    }
   ]
  },
  { "title": "Wallets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Available Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "yaxes": [
    { "format": "FIL" }
   ],
   "targets": [
    {
     "expr": "lotus_wallet_balance{job=\"$job\",miner_id=\"$miner_id\", address=\"$miner_id\"}",
     "legendFormat": "Miner"
    },
    {
     "expr": "lotus_wallet_balance{job=\"$job\",miner_id=\"$miner_id\", address=\"$owner_addr\"}",
     "legendFormat": "Owner"
    },
    {
     "expr": "lotus_wallet_balance{job=\"$job\",miner_id=\"$miner_id\", address=\"$worker_addr\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "lotus_wallet_balance{job=\"$job\",miner_id=\"$miner_id\", address=\"$control0_addr\"}",
     "legendFormat": "Control0"
    }
   ]
  },
  {
   "title": "Locked Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "yaxes": [
    { "format": "Fil" }
   ],
   "targets": [
    {
     "expr": "lotus_wallet_locked_balance{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "{{locked_type}}"
    }
   ]
  },
  {
   "title": "Other Wallet Balances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "yaxes": [
    { "format": "Fil" }
   ],
   "targets": [
    {
     "expr": "lotus_wallet_balance {job=\"$job\",miner_id=\"$miner_id\",address!~\"$worker_addr|$owner_addr|$control0_addr|$miner_id\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Verified datacap available",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "lotus_wallet_verified_datacap{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Miner Total Trafic ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "bps", "label": "Bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(lotus_miner_net_total_in{job=\"$job\",miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(lotus_miner_net_total_out{job=\"$job\",miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Miner Total Trafic  per protocol",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
   "yaxes": [
    { "format": "bps", "label": "Bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(lotus_miner_net_protocol_in{job=\"$job\",miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "{{protocol}} - Receive"
    },
    {
     "expr": "rate(lotus_miner_net_protocol_out{job=\"$job\",miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "{{protocol}} - Transmit"
    }
   ]
  },
  {
   "title": "Netpeers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "lotus_netpeers_total{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "lotus_miner_netpeers_total{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Miner"
    }
   ]
  },
  {
   "title": "Daemon Total Trafic ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "bps", "label": "Bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(lotus_net_total_in{job=\"$job\",miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(lotus_net_total_out{job=\"$job\",miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Daemon Total Trafic  per protocol",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 96 },
   "yaxes": [
    { "format": "bps", "label": "Bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(lotus_net_protocol_in{job=\"$job\",miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "{{protocol}} - Receive"
    },
    {
     "expr": "rate(lotus_net_protocol_out{job=\"$job\",miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "{{protocol}} - Transmit"
    }
   ]
  },
  {
   "title": "Worker - Ressources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "repeat": "worker",
   "collapsed": true,
   "panels": [
    {
     "title": "$worker_host - CPU",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 104 },
     "repeat": "worker_host",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_worker_cpu_used{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_worker_cpu{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-lotus_miner_worker_cpu_used{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_worker_cpu{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$worker_host - GPU",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 104 },
     "repeat": "worker_host",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_worker_gpu_used{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_worker_gpu{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-lotus_miner_worker_gpu_used{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_worker_gpu{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$worker_host - Physical Memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 104 },
     "repeat": "worker_host",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_worker_ram_tasks{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_worker_ram_reserved{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "lotus_miner_worker_ram_total{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-(lotus_miner_worker_ram_reserved{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_ram_tasks{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"})",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_worker_ram_total{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$worker_host - VMEM (RAM + Swap)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 104 },
     "repeat": "worker_host",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_worker_vmem_tasks{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_worker_vmem_reserved{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "lotus_miner_worker_vmem_total{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-lotus_miner_worker_vmem_tasks{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-lotus_miner_worker_vmem_reserved{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_worker_vmem_total{job=\"$job\",miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "$storage_id",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 105 },
     "repeat": "storage_id",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_storage_capacity{job=\"$job\",miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_available{job=\"$job\",miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_reserved{job=\"$job\",miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_storage_reserved{job=\"$job\",miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "lotus_miner_storage_available{job=\"$job\",miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_storage_capacity{job=\"$job\",miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Mpool messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "yaxes": [
    { "format": "msgs" }
   ],
   "targets": [
    {
     "expr": "lotus_mpool_total{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": " Mpool pending"
    }
   ]
  },
  {
   "title": "Chain Workers Sync Diff with ChainHead",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "lotus_chain_sync_diff{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Worker {{ worker_id }}"
    }
   ]
  },
  {
   "title": "Mining Eligibility",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "lotus_power_mining_eligibility{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Eligibility"
    }
   ]
  },
  {
   "title": "Scrape time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "lotus_scrape_duration_seconds{job=\"$job\",collector!=\"\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Deadlines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Number of sectors" }
   ],
   "targets": [
    {
     "expr": "lotus_miner_deadline_active_sectors_all{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "{{ index }} - All"
    },
    {
     "expr": "lotus_miner_deadline_active_sectors_recovering{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "{{ index }} - Recovering"
    },
    {
     "expr": "lotus_miner_deadline_active_sectors_faulty{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "{{ index }} - Faulty"
    }
   ]
  },
  {
   "title": "Stored sectors STATE",
   "type": "graph",
   "description": "Expired sectors are proving sectors consuming space on the miner harddrive but no counting in the Raw Power",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "count by (state) (lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\" })",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "count(lotus_miner_sector_state{state=\"Proving\", job=\"$job\",miner_id=\"$miner_id\"} unless on (sector_id) lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"})",
     "legendFormat": "Expired"
    }
   ]
  },
  {
   "title": "Miner Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "Capacity" }
   ],
   "targets": [
    {
     "expr": "lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"miner\"}",
     "legendFormat": "{{power_type}}"
    },
    {
     "expr": "sum( lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"} * on(miner_id) group_left () lotus_miner_info_sector_size{job=\"$job\",miner_id=\"$miner_id\"})",
     "legendFormat": "Committed Power"
    },
    {
     "expr": "sum(lotus_miner_sector_qa_power{job=\"$job\",miner_id=\"$miner_id\"} * on(sector_id) group_left () lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"})",
     "legendFormat": "Max QA Power"
    }
   ]
  },
  {
   "title": "Average Sealing Duration (From Packed to Finalized)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "yaxes": [
    { "format": "dthms" }
   ],
   "targets": [
    {
     "expr": "quantile(0.5, (topk(10,lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"finalized\"}) - on (sector_id) lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"packed\"}) and on(sector_id) lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", state=\"Proving\"})",
     "legendFormat": "Last 10 Sectors"
    },
    {
     "expr": "quantile(0.5, (topk(100,lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"finalized\"}) - on (sector_id) lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"packed\"}) and on(sector_id) lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", state=\"Proving\"})",
     "legendFormat": "Last 100 Sectors"
    },
    {
     "expr": "quantile(0.5, (lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"finalized\"} - on (sector_id) lotus_miner_sector_event{job=\"$job\",miner_id=\"$miner_id\", event_type=\"packed\"}) and on(sector_id) lotus_miner_sector_state{job=\"$job\",miner_id=\"$miner_id\", state=\"Proving\"})",
     "legendFormat": "All times"
    }
   ]
  },
  {
   "title": "Power estimation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "yaxes": [
    { "format": "blocks", "label": "blocks / day" }
   ],
   "targets": [
    {
     "expr": "sum(lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"miner\", power_type=\"QualityAdjPower\"})/sum(lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"network\",power_type=\"QualityAdjPower\"})*5*60*2*24",
     "legendFormat": "Mining rate"
    },
    {
     "expr": "sum(lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"miner\", power_type=\"QualityAdjPower\"})/sum(lotus_power{job=\"$job\",miner_id=\"$miner_id\", scope=\"network\",power_type=\"QualityAdjPower\"})",
     "legendFormat": "Power rate"
    }
   ]
  },
  {
   "title": "Local Mpool  Queuing msg",
   "type": "graph",
   "description": "Represent queuing message in mpool message if they don't stay in mpool more than 1 minute may not being counted",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "count by (from, method) (lotus_mpool_local_message{job=\"$job\",miner_id=\"$miner_id\"})",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Basefee History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "nfarad" } },
   "yaxes": [
    { "format": "nfarad" }
   ],
   "targets": [
    {
     "expr": "lotus_chain_basefee{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Basefee"
    }
   ]
  },
  {
   "title": "Sector State per deadline",
   "type": "table",
   "description": "Repair/restore the Faulty sectors and run : lotus-miner proving check",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 127 },
   "targets": [
    {
     "expr": "lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": " Expired Proving Sector",
   "type": "table",
   "description": "Sectors that are expired but still proving and consumming space on the miner",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 134 },
   "targets": [
    {
     "expr": "lotus_miner_sector_state{state=\"Proving\", job=\"$job\",miner_id=\"$miner_id\"} unless on (sector_id) lotus_miner_deadline_active_partition_sector{job=\"$job\",miner_id=\"$miner_id\"}",
     "legendFormat": "Expired sectors"
    }
   ]
  }
 ]
}