{
 "title": "LOTUS farcaster",
 "description": "A Filecoin lotus dashboard for miners",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "miner_id", "label": "Miner ID", "query": "label_values(miner_id)" },
   {
    "name": "worker_addr",
    "label": "Worker Address",
    "query": "label_values(test_lotus_miner_info{miner_id=\"$miner_id\"},worker_addr)"
   },
   {
    "name": "owner_addr",
    "label": "Owner Address",
    "query": "label_values(test_lotus_miner_info{miner_id=\"$miner_id\"},owner_addr)"
   },
   {
    "name": "control0_addr",
    "label": "Control Address 0",
    "query": "label_values(test_lotus_miner_info{miner_id=\"$miner_id\"},control0_addr)"
   },
   {
    "name": "worker_name",
    "label": "Worker",
    "query": "query_result(sort(test_lotus_miner_worker_id{miner_id=\"$miner_id\"}))"
   },
   {
    "name": "storage_id",
    "label": "Storage",
    "query": "label_values(test_lotus_miner_storage_info{miner_id=\"$miner_id\"},storage_id)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last update",
   "type": "table",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "test_lotus_daemon_info{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Daemon Version",
   "type": "table",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "test_lotus_daemon_info{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Miner Version",
   "type": "table",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "test_lotus_miner_info{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Is onSync",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "test_lotus_daemon_chain_sync_status{miner_id=\"$miner_id\"}",
     "legendFormat": "Worker {{ worker_id }}"
    }
   ]
  },
  {
   "title": "Sealing jobs All (running VS waiting)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "count by (task) (test_lotus_miner_worker_job{miner_id=\"$miner_id\"})"
    },
    {
     "expr": "count (test_lotus_miner_worker_job{miner_id=\"$miner_id\", runwait!=\"0\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count (test_lotus_miner_worker_id{miner_id=\"$miner_id\"})",
     "legendFormat": "Number of Workers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "test_lotus_daemon_height{miner_id=\"$miner_id\"}",
     "legendFormat": "Chain Head"
    }
   ]
  },
  {
   "title": "Network",
   "type": "table",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "test_lotus_daemon_info{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "test_lotus_power_mining_eligibility{miner_id=\"$miner_id\"}",
     "legendFormat": "Mining"
    }
   ]
  },
  {
   "title": "Netpeers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "test_lotus_netpeers_total{miner_id=\"$miner_id\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Number of sealing jobs",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (task) (test_lotus_miner_worker_job{miner_id=\"$miner_id\"})",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Ressources - $worker_name",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
   "repeat": "worker_name",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg((test_lotus_miner_worker_cpu_used{miner_id=\"$miner_id\", worker_name=\"$worker_name\"})/(test_lotus_miner_worker_cpu{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}) >= 0)",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg((test_lotus_miner_worker_gpu_used{miner_id=\"$miner_id\", worker_name=\"$worker_name\"})/(test_lotus_miner_worker_gpu{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}) >= 0)",
     "legendFormat": "GPU"
    },
    {
     "expr": "avg((test_lotus_miner_worker_mem_reserved{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}+test_lotus_miner_worker_mem_physical_used{miner_id=\"$miner_id\", worker_name=\"$worker_name\"})/(test_lotus_miner_worker_mem_physical{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}) >= 0)",
     "legendFormat": "RAM"
    },
    {
     "expr": "avg((test_lotus_miner_worker_mem_reserved{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}+test_lotus_miner_worker_mem_vmem_used{miner_id=\"$miner_id\", worker_name=\"$worker_name\"})/(test_lotus_miner_worker_mem_physical{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}+test_lotus_miner_worker_mem_swap{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}) >= 0)",
     "legendFormat": "VMEM"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(test_lotus_power{miner_id=\"$miner_id\", scope=\"miner\", powertype=\"QualityAdjPower\"})/sum(test_lotus_power{miner_id=\"$miner_id\", scope=\"network\",powertype=\"QualityAdjPower\"})"
    }
   ]
  },
  {
   "title": "Miner Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "test_lotus_power{miner_id=\"$miner_id\", scope=\"miner\"}",
     "legendFormat": "{{powertype}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "/ day" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(test_lotus_power{miner_id=\"$miner_id\", scope=\"miner\", powertype=\"QualityAdjPower\"})/sum(test_lotus_power{miner_id=\"$miner_id\", scope=\"network\",powertype=\"QualityAdjPower\"})*5*60*2*24"
    }
   ]
  },
  {
   "title": "Sealing jobs",
   "type": "table",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "test_lotus_miner_worker_job{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1/(sum(test_lotus_power{miner_id=\"$miner_id\", scope=\"miner\", powertype=\"QualityAdjPower\"})/sum(test_lotus_power{miner_id=\"$miner_id\", scope=\"network\",powertype=\"QualityAdjPower\"})*2*5/60)"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "test_lotus_miner_storage_info{miner_id=\"$miner_id\"}",
     "legendFormat": "{{storage_url}} - CanSeal {{canseal}}"
    },
    {
     "expr": "test_lotus_miner_storage_available{miner_id=\"$miner_id\"} "
    },
    {
     "expr": "test_lotus_miner_storage_available{miner_id=\"$miner_id\"} /test_lotus_miner_storage_capacity{miner_id=\"$miner_id\"} "
    }
   ]
  },
  {
   "title": "Available Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "test_lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$miner_id\"}",
     "legendFormat": "Miner"
    },
    {
     "expr": "test_lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$owner_addr\"}",
     "legendFormat": "Owner"
    },
    {
     "expr": "test_lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$worker_addr\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "test_lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$control0_addr\"}",
     "legendFormat": "Control0"
    }
   ]
  },
  {
   "title": "Locked Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "test_lotus_wallet_locked_balance{miner_id=\"$miner_id\"}",
     "legendFormat": "{{locked_type}}"
    }
   ]
  },
  {
   "title": "Other Wallet Balances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "test_lotus_wallet_balance {miner_id=\"$miner_id\",address!~\"$worker_addr|$owner_addr|$control_addr|$miner_id\"}",
     "legendFormat": "{{short}}"
    }
   ]
  },
  {
   "title": "Proving sectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (state) (test_lotus_miner_sector_state{miner_id=\"$miner_id\", state=\"Proving\"})"
    }
   ]
  },
  {
   "title": "Number of sectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 2, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (state) (test_lotus_miner_sector_state{miner_id=\"$miner_id\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "test_lotus_mpool_total{miner_id=\"$miner_id\"}",
     "legendFormat": " Mpool pending"
    }
   ]
  },
  {
   "title": "Local Mpool Pending messages",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 2, "y": 26 },
   "targets": [
    {
     "expr": "test_lotus_mpool_local_message{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "test_lotus_mpool_local_total{miner_id=\"$miner_id\"}",
     "legendFormat": "Local mpool pending"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Stored sectors STATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "count by (state) (test_lotus_miner_sector_state{miner_id=\"$miner_id\" })",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Sealing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Sealing jobs Running details",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "count by (task) (test_lotus_miner_worker_job{miner_id=\"$miner_id\", runwait=\"0\"})"
    }
   ]
  },
  {
   "title": "Sealing jobs Waiting details",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "count by (task) (test_lotus_miner_worker_job{miner_id=\"$miner_id\", runwait!=\"0\"})"
    }
   ]
  },
  {
   "title": "Sealing ERRORS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "count by (state) (test_lotus_miner_sector_state{miner_id=\"$miner_id\" })",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Wallets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Available Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "yaxes": [
    { "format": "FIL" }
   ],
   "targets": [
    {
     "expr": "test_lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$miner_id\"}",
     "legendFormat": "Miner"
    },
    {
     "expr": "test_lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$owner_addr\"}",
     "legendFormat": "Owner"
    },
    {
     "expr": "test_lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$worker_addr\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "test_lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$control0_addr\"}",
     "legendFormat": "Control0"
    }
   ]
  },
  {
   "title": "Locked Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "yaxes": [
    { "format": "Fil" }
   ],
   "targets": [
    {
     "expr": "test_lotus_wallet_locked_balance{miner_id=\"$miner_id\"}",
     "legendFormat": "{{locked_type}}"
    }
   ]
  },
  {
   "title": "Other Wallet Balances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "yaxes": [
    { "format": "Fil" }
   ],
   "targets": [
    {
     "expr": "test_lotus_wallet_balance {miner_id=\"$miner_id\",address!~\"$worker_addr|$owner_addr|$control_addr|$miner_id\"}",
     "legendFormat": "{{short}}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Miner Total Trafic ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bps", "label": "Bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(test_lotus_net_total_in{miner_id=\"$miner_id\", service=\"miner\"}[1m])",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(test_lotus_net_total_out{miner_id=\"$miner_id\", service=\"miner\"}[1m])",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Miner Total Trafic  per protocol",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "bps", "label": "Bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(test_lotus_net_protocol_in{miner_id=\"$miner_id\", service=\"miner\"}[1m])",
     "legendFormat": "{{protocols}} - Receive"
    },
    {
     "expr": "rate(test_lotus_net_protocol_out{miner_id=\"$miner_id\", service=\"miner\"}[1m])",
     "legendFormat": "{{protocols}} - Transmit"
    }
   ]
  },
  {
   "title": "Netpeers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "test_lotus_netpeers_total{miner_id=\"$miner_id\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Daemon Total Trafic ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bps", "label": "Bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(test_lotus_net_total_in{miner_id=\"$miner_id\", service=\"daemon\"}[1m])",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(test_lotus_net_total_out{miner_id=\"$miner_id\", service=\"daemon\"}[1m])",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Daemon Total Trafic  per protocol",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "bps", "label": "Bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(test_lotus_net_protocol_in{miner_id=\"$miner_id\", service=\"daemon\"}[1m])",
     "legendFormat": "{{protocols}} - Receive"
    },
    {
     "expr": "rate(test_lotus_net_protocol_out{miner_id=\"$miner_id\", service=\"daemon\"}[1m])",
     "legendFormat": "{{protocols}} - Transmit"
    }
   ]
  },
  { "title": "$worker - Ressources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 }, "repeat": "worker" },
  {
   "title": "$worker_name - CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 72 },
   "repeat": "worker_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "test_lotus_miner_worker_cpu_used{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "test_lotus_miner_worker_cpu{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}-test_lotus_miner_worker_cpu_used{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "test_lotus_miner_worker_cpu{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$worker_name - GPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 72 },
   "repeat": "worker_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "test_lotus_miner_worker_gpu_used{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "test_lotus_miner_worker_gpu{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}-test_lotus_miner_worker_gpu_used{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "test_lotus_miner_worker_gpu{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$worker_name - Physical Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 72 },
   "repeat": "worker_name",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "test_lotus_miner_worker_mem_physical_used{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "test_lotus_miner_worker_mem_reserved{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "test_lotus_miner_worker_mem_physical{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}-(test_lotus_miner_worker_mem_reserved{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}+test_lotus_miner_worker_mem_physical_used{miner_id=\"$miner_id\", worker_name=\"$worker_name\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "test_lotus_miner_worker_mem_physical{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$worker_name - VMem (Physical + Swap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 72 },
   "repeat": "worker_name",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "test_lotus_miner_worker_mem_vmem_used{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "test_lotus_miner_worker_mem_reserved{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "(test_lotus_miner_worker_mem_physical{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}+test_lotus_miner_worker_mem_swap{miner_id=\"$miner_id\", worker_name=\"$worker_name\"})-(test_lotus_miner_worker_mem_reserved{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}+test_lotus_miner_worker_mem_vmem_used{miner_id=\"$miner_id\", worker_name=\"$worker_name\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "test_lotus_miner_worker_mem_physical{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}+test_lotus_miner_worker_mem_swap{miner_id=\"$miner_id\", worker_name=\"$worker_name\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "$storage_id",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 98 },
   "repeat": "storage_id",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "test_lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-test_lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-test_lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "test_lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "test_lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "test_lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Scrape time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "test_lotus_miner_scrape_duration_seconds{collector!=\"\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Chain Workers Sync Diff with ChainHead",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "test_lotus_daemon_chain_sync_diff{miner_id=\"$miner_id\"}",
     "legendFormat": "Worker {{ worker_id }}"
    }
   ]
  },
  {
   "title": "Mining Eligibility",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "test_lotus_power_mining_eligibility{miner_id=\"$miner_id\"}",
     "legendFormat": "Eligibility"
    }
   ]
  }
 ]
}